# Sprint 1 - Day 6
# Data Quality Manual Review

Objective:
- Connect to the SQLite database
- Review all datasets manually
- Check schema and data types
- Identify missing values
- Identify duplicate records
- Review summary statistics
- Document observations for each dataset

In [15]:
import sqlite3
import pandas as pd

db_path = "../db/nifty100.db"

conn = sqlite3.connect(db_path)

print("Connected Successfully!")

Connected Successfully!

In [16]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = pd.read_sql(query, conn)

tables

                name
0           analysis
1      balance_sheet
2          cash_flow
3          companies
4          documents
5    profit_and_loss
6      pros_and_cons
7   financial_ratios
8         market_cap
9        peer_groups
10           sectors
11      stock_prices

In [17]:
def review_table(table_name):
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn)

    print("=" * 80)
    print(f"Table: {table_name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nFirst Five Rows:")
    display(df.head())

    return df

In [18]:
companies = review_table("companies")

================================================================================
Table: companies
================================================================================

Shape:
(92, 12)

Columns:
['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

Data Types:
id                     str
company_logo           str
company_name           str
chart_link             str
about_company          str
website                str
nse_profile            str
bse_profile            str
face_value         float64
book_value         float64
roce_percentage    float64
roe_percentage     float64
dtype: object

Missing Values:
id                 0
company_logo       1
company_name       0
chart_link         0
about_company      0
website            1
nse_profile        1
bse_profile        1
face_value         1
book_value         1
roce_percentage    1
roe_percentage     2
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

In [22]:
table_names = tables["name"].tolist()

for table in table_names:
    review_table(table)

================================================================================
Table: analysis
================================================================================

Shape:
(20, 6)

Columns:
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']

Data Types:
id                          int64
company_id                    str
compounded_sales_growth       str
compounded_profit_growth      str
stock_price_cagr              str
roe                           str
dtype: object

Missing Values:
id                          0
company_id                  0
compounded_sales_growth     0
compounded_profit_growth    0
stock_price_cagr            0
roe                         0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
2,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
3,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
4,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%

================================================================================
Table: balance_sheet
================================================================================

Shape:
(1312, 13)

Columns:
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

Data Types:
id                     int64
company_id               str
year                     str
equity_capital       float64
reserves               int64
borrowings             int64
other_liabilities      int64
total_liabilities      int64
fixed_assets           int64
cwip                   int64
investments            int64
other_asset            int64
total_assets           int64
dtype: object

Missing Values:
id                   0
company_id           0
year                 0
equity_capital       0
reserves             0
borrowings           0
other_liabilities    0
total_liabilities    0
fixed_assets         0
cwip                 0
investments          0
other_asset          0
total_assets         0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
0,136,ABB,Dec 2012,21.0,626,0,260,907,109,1,0,798,907
1,137,ABB,Mar 2014,21.0,767,0,351,1139,98,1,0,1040,1139
2,138,ABB,Mar 2015,21.0,916,0,436,1374,96,4,0,1274,1374
3,139,ABB,Mar 2016,21.0,1174,0,421,1616,108,3,0,1505,1616
4,140,ABB,Mar 2017,21.0,1366,0,679,2066,110,6,0,1950,2066

================================================================================
Table: cash_flow
================================================================================

Shape:
(1187, 7)

Columns:
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

Data Types:
id                      int64
company_id                str
year                      str
operating_activity    float64
investing_activity    float64
financing_activity    float64
net_cash_flow         float64
dtype: object

Missing Values:
id                    0
company_id            0
year                  0
operating_activity    2
investing_activity    2
financing_activity    2
net_cash_flow         2
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,Mar-13,11615.0,-6038.0,-5729.0,-152.0
1,38,TCS,Mar-14,14751.0,-9452.0,-5673.0,-374.0
2,39,TCS,Mar-15,19369.0,-1807.0,-17168.0,394.0
3,40,TCS,Mar-16,19109.0,-5010.0,-9666.0,4433.0
4,41,TCS,Mar-17,25223.0,-16895.0,-11026.0,-2698.0

================================================================================
Table: companies
================================================================================

Shape:
(92, 12)

Columns:
['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

Data Types:
id                     str
company_logo           str
company_name           str
chart_link             str
about_company          str
website                str
nse_profile            str
bse_profile            str
face_value         float64
book_value         float64
roce_percentage    float64
roe_percentage     float64
dtype: object

Missing Values:
id                 0
company_logo       1
company_name       0
chart_link         0
about_company      0
website            1
nse_profile        1
bse_profile        1
face_value         1
book_value         1
roce_percentage    1
roe_percentage     2
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

================================================================================
Table: documents
================================================================================

Shape:
(1585, 4)

Columns:
['id', 'company_id', 'year', 'annual_report']

Data Types:
id               int64
company_id         str
year             int64
annual_report      str
dtype: object

Missing Values:
id                0
company_id        0
year              0
annual_report    52
dtype: int64

Duplicate Rows:
0

First Five Rows:

   id company_id  year                                      annual_report
0   1        ABB  2024  https://www.bseindia.com/xml-data/corpfiling/A...
1   2        ABB  2023  https://www.bseindia.com/xml-data/corpfiling/A...
2   3        ABB  2022  https://www.bseindia.com/bseplus/AnnualReport/...
3   4        ABB  2021  https://www.bseindia.com/bseplus/AnnualReport/...
4   5        ABB  2020  https://www.bseindia.com/bseplus/AnnualReport/...

================================================================================
Table: profit_and_loss
================================================================================

Shape:
(1276, 15)

Columns:
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

Data Types:
id                     int64
company_id               str
year                     str
sales                  int64
expenses               int64
operating_profit     float64
opm_percentage       float64
other_income           int64
interest               int64
depreciation           int64
profit_before_tax      int64
tax_percentage       float64
net_profit             int64
eps                  float64
dividend_payout      float64
dtype: object

Missing Values:
id                     0
company_id             0
year                   0
sales                  0
expenses               0
operating_profit      13
opm_percentage        15
other_income           0
interest               0
depreciation           0
profit_before_tax      0
tax_percentage        95
net_profit             0
eps                    5
dividend_payout      103
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

================================================================================
Table: pros_and_cons
================================================================================

Shape:
(16, 4)

Columns:
['id', 'company_id', 'pros', 'cons']

Data Types:
id            int64
company_id      str
pros            str
cons            str
dtype: object

Missing Values:
id            0
company_id    0
pros          5
cons          1
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,pros,cons
0,1,HDFCBANK,Company is expected to give good quarter,Stock is trading at 2.76 times its book value
1,2,HDFCBANK,Company has delivered good profit growth of 23...,Company has low interest coverage ratio.
2,3,HDFCBANK,Company has been maintaining a healthy dividen...,"Contingent liabilities of Rs.24,09,821 Cr."
3,4,HDFCBANK,Company's median sales growth is 16.4% of last...,"Earnings include an other income of Rs.1,55,87..."
4,5,SBILIFE,Company is almost debt free.,Stock is trading at 9.11 times its book value

================================================================================
Table: financial_ratios
================================================================================

Shape:
(1184, 16)

Columns:
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']

Data Types:
id                               int64
company_id                         str
year                               str
net_profit_margin_pct          float64
operating_profit_margin_pct    float64
return_on_equity_pct           float64
debt_to_equity                 float64
interest_coverage              float64
asset_turnover                 float64
free_cash_flow_cr              float64
capex_cr                       float64
earnings_per_share             float64
book_value_per_share           float64
dividend_payout_ratio_pct      float64
total_debt_cr                    int64
cash_from_operations_cr        float64
dtype: object

Missing Values:
id                              0
company_id                      0
year                            0
net_profit_margin_pct           1
operating_profit_margin_pct    61
return_on_equity_pct            0
debt_to_equity                  0
interest_coverage              93
asset_turnover                  1
free_cash_flow_cr               2
capex_cr                        2
earnings_per_share              4
book_value_per_share            0
dividend_payout_ratio_pct       4
total_debt_cr                   0
cash_from_operations_cr         2
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,earnings_per_share,book_value_per_share,dividend_payout_ratio_pct,total_debt_cr,cash_from_operations_cr
0,1,ABB,Dec 2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,68.0,3.0810,25.0,0,101.0
1,2,ABB,Mar 2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,93.0,3.7524,25.0,0,155.0
2,3,ABB,Mar 2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,93.0,3.7524,25.0,0,0.0
3,4,ABB,Mar 2015,10.00,14.0,24.44,0.0,NaN,1.6659,28.0,187.0,108.0,4.4619,29.0,0,215.0
4,5,ABB,Mar 2015,10.00,14.0,24.44,0.0,NaN,1.6659,-1899.0,1864.0,108.0,4.4619,29.0,0,-35.0

================================================================================
Table: market_cap
================================================================================

Shape:
(552, 9)

Columns:
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

Data Types:
id                          int64
company_id                    str
year                        int64
market_cap_crore          float64
enterprise_value_crore    float64
pe_ratio                  float64
pb_ratio                  float64
ev_ebitda                 float64
dividend_yield_pct        float64
dtype: object

Missing Values:
id                        0
company_id                0
year                      0
market_cap_crore          0
enterprise_value_crore    0
pe_ratio                  0
pb_ratio                  0
ev_ebitda                 0
dividend_yield_pct        0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,year,market_cap_crore,enterprise_value_crore,pe_ratio,pb_ratio,ev_ebitda,dividend_yield_pct
0,1,ABB,2019,844312.98,814410.48,19.29,14.26,22.84,0.84
1,2,ABB,2020,923674.33,1120679.72,67.54,13.03,24.93,3.90
2,3,ABB,2021,1020674.09,1166450.81,62.63,6.67,7.58,1.58
3,4,ABB,2022,1185994.82,1158637.42,18.68,4.75,6.12,3.35
4,5,ABB,2023,1161513.28,1103083.77,58.34,12.72,5.70,1.05

================================================================================
Table: peer_groups
================================================================================

Shape:
(56, 4)

Columns:
['id', 'peer_group_name', 'company_id', 'is_benchmark']

Data Types:
id                 int64
peer_group_name      str
company_id           str
is_benchmark       int64
dtype: object

Missing Values:
id                 0
peer_group_name    0
company_id         0
is_benchmark       0
dtype: int64

Duplicate Rows:
0

First Five Rows:

   id peer_group_name  company_id  is_benchmark
0   1   Private Banks    HDFCBANK             1
1   2   Private Banks   ICICIBANK             0
2   3   Private Banks    AXISBANK             0
3   4   Private Banks   KOTAKBANK             0
4   5   Private Banks  INDUSINDBK             0

================================================================================
Table: sectors
================================================================================

Shape:
(92, 6)

Columns:
['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']

Data Types:
id                       int64
company_id                 str
broad_sector               str
sub_sector                 str
index_weight_pct       float64
market_cap_category        str
dtype: object

Missing Values:
id                     0
company_id             0
broad_sector           0
sub_sector             0
index_weight_pct       0
market_cap_category    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,broad_sector,sub_sector,index_weight_pct,market_cap_category
0,1,ABB,Industrials,Capital Goods,0.81,Large Cap
1,2,ADANIENSOL,Energy,Power & Utilities,0.65,Large Cap
2,3,ADANIENT,Industrials,Conglomerates,1.50,Large Cap
3,4,ADANIGREEN,Energy,Renewable Energy,1.23,Large Cap
4,5,ADANIPORTS,Industrials,Infrastructure,2.12,Large Cap

================================================================================
Table: stock_prices
================================================================================

Shape:
(5520, 9)

Columns:
['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']

Data Types:
id                  int64
company_id            str
date                  str
open_price        float64
high_price        float64
low_price         float64
close_price       float64
volume              int64
adjusted_close    float64
dtype: object

Missing Values:
id                0
company_id        0
date              0
open_price        0
high_price        0
low_price         0
close_price       0
volume            0
adjusted_close    0
dtype: int64

Duplicate Rows:
0

First Five Rows:

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

In [26]:
summary = []

for table in table_names:
    df = pd.read_sql(f"SELECT * FROM {table}", conn)

    summary.append({
        "Table": table,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

               Table  Rows  Columns  Missing Values  Duplicate Rows
0           analysis    20        6               0               0
1      balance_sheet  1312       13               0               0
2          cash_flow  1187        7               8               0
3          companies    92       12               9               0
4          documents  1585        4              52               0
5    profit_and_loss  1276       15             231               0
6      pros_and_cons    16        4               6               0
7   financial_ratios  1184       16             170               0
8         market_cap   552        9               0               0
9        peer_groups    56        4               0               0
10           sectors    92        6               0               0
11      stock_prices  5520        9               0               0

In [27]:
summary_df.to_csv("../outputs/data_quality_summary.csv", index=False)

print("Data Quality Summary saved successfully!")

Data Quality Summary saved successfully!

In [29]:
summary_df.to_csv("../outputs/data_quality_summary.csv", index=False)